### ISSUE TITLE
Build issue?

### ISSUE THREAD

**Issue by mr-stivo** [a2-4am/untitled-word-game-pro#1]
Not much of an issue but I had a problem building it. At least it got me to finally update my version of cadius. =)

The Makefile says:
```
# https://github.com/mach-kernel/cadius
# version 1.4.0 or later
CADIUS=cadius
```

But using 1.4.0 generates:
```
cadius v 1.4.0 (c) Brutal Deluxe 2011-2013.
  Error : Invalid volume size : '140KB'.
```

I think it needs version 1.4.4 or later:
```
1.4.4
Fix 140KiB volume size assertion (thanks [@inexorabletash]
```

Much faster than untitled-word-game but I found it's whole encoding technique and the links in the readme very interesting. Good job on this!

**Comment by a2-4am** [comment]
Thank you!
